name: Dockerhub

on:
  push:
    branches:
      - "main"
  #   tags:
  #     - "*"
  # pull_request:
  #   branches:
  #     - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/gitea_runner_dind:latest
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
